import Foundation

struct ChannelDetail: Codable {
    let name: String
    let id: String
    let url: String
    
    let banners: [Image]
    let thumbnails: [Image]
    let subCount: Int
    let totalViews: Int
    let joined: Int
    
    let paid: Bool
    let autoGenerated: Bool
    let isFamilyFriendly: Bool
    let description: String
    let descriptionHTML: String
    let allowedRegions: [String]
    
    let latestVideos: [Video]
    let relatedChannels: [RelatedChannel]
    
    struct Image: Codable {
        let url: String
        let width: Int
        let height: Int
    }
    
    struct RelatedChannel: Codable {
        let name: String
        let id: String
        let url: String
        let thumbnails: [Image]
        
        enum CodinKeys: String, CodingKey {
            case name = "author"
            case id = "authorId"
            case url = "authorUrl"
            case thumbnails = "authorThumbnails"
        }
    }
    
    enum CodingKeys: String, CodingKey {
        case name = "author"
        case id = "authorId"
        case url = "authorUrl"
        
        case banners = "authorBanners"
        case thumbnails = "authorThumbnails"
        case subCount
        case totalViews
        case joined
        
        case paid
        case autoGenerated
        case isFamilyFriendly
        case description
        case descriptionHTML = "descriptionHtml"
        case allowedRegions
        
        case latestVideos
        case relatedChannels
    }
}
